
CREATE FUNCTION [dbo].[FN_split_by]
(
   @List NVARCHAR(MAX),
   @Delimiter NVARCHAR(1)
)
RETURNS TABLE
WITH SCHEMABINDING AS
RETURN
     -- SOLVIN
     -- 2014-10-13 Florian
     -- 2014-11-05 Florian: bugfix last part
  WITH E1(N)        AS ( SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1),
       E2(N)        AS (SELECT 1 FROM E1 a, E1 b),
       E4(N)        AS (SELECT 1 FROM E2 a, E2 b),
       E8(N)        AS (SELECT 1 FROM E4 a, E2 b),
       cteTally(N)  AS (SELECT TOP (DATALENGTH(ISNULL(@List,N''))/2) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) FROM E8),
       cteStart(N1) AS (SELECT 0 UNION ALL SELECT t.N+1 FROM cteTally t WHERE (SUBSTRING(@List,t.N,1) = @Delimiter))
  SELECT Item = SUBSTRING(@List, s.N1, ISNULL(NULLIF(CHARINDEX(@Delimiter,@List,s.N1),0)-s.N1,DATALENGTH(ISNULL(@List,N''))/2+1))
    FROM cteStart s;
